/**
 * generated by Xtext 2.12.0
 */
package sensorDeploymentLanguage.ide;

import sensorDeploymentLanguage.ide.AbstractDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DSLIdeModule extends AbstractDSLIdeModule {
}
