/*
 * generated by Xtext
 */
package visualizationDesignLanguage.DSL;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VDRuntimeModule extends visualizationDesignLanguage.DSL.AbstractVDRuntimeModule {

}
