/*
* generated by Xtext
*/
package visualizationDesignLanguage.DSL;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class VDStandaloneSetup extends VDStandaloneSetupGenerated{

	public static void doSetup() {
		new VDStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

