/*
* generated by Xtext
*/
package requirementEngineering.DSL;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RequirementEngineeringStandaloneSetup extends RequirementEngineeringStandaloneSetupGenerated{

	public static void doSetup() {
		new RequirementEngineeringStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

