/*
 * generated by Xtext
 */
package requirementEngineering.DSL;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RequirementEngineeringRuntimeModule extends requirementEngineering.DSL.AbstractRequirementEngineeringRuntimeModule {

}
