/*
 * generated by Xtext
 */
package sensorDeploymentLanguage.DSL;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SDRuntimeModule extends sensorDeploymentLanguage.DSL.AbstractSDRuntimeModule {

}
