/*
* generated by Xtext
*/
package sensorDeploymentLanguage.DSL;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SDStandaloneSetup extends SDStandaloneSetupGenerated{

	public static void doSetup() {
		new SDStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

