/*
 * generated by Xtext 2.12.0
 */
package visualizationDesignLanguage.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import visualizationDesignLanguage.DSL.ui.internal.DSLActivator;

public class DSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DSLActivator.getInstance().getInjector("visualizationDesignLanguage.DSL");
	}

}
